### ISSUE TITLE
Dangerous code

### ISSUE THREAD

**Issue by ghost** [pr0crustes/SmoothTable#2]
https://github.com/pr0crustes/SmoothTable/blob/4b459b348766ee95d01790a2fa7d736b7e988a73/src/tweak/SmoothTable.xm#L81

`-[NSBundle bundleIdentifier]` can return `nil`, resulting in crashing of the processes that do not have the bundle identifier because `-[NSString stringByAppendingString:]` expects a non-nil argument. A prominent example is `replayd` that would keep constantly crashing and draining battery. You should fix this as soon as possible.

**Comment by pr0crustes** [comment]
Fixed, thank you!
