### ISSUE TITLE
Caused crashes in TVRemoteConnectionService

### ISSUE THREAD

**Issue by ghost** [pr0crustes/SmoothTable#4]
cr4shed crashlog: [https://pastebin.com/0Pj1evPe](https://pastebin.com/0Pj1evPe) basically everything was working fine, but it started crashing when i played a game (not sure if its the cause but the game is Phoenix II? bundle id: com.firigames.phoenixii)

**Comment by pr0crustes** [comment]
Should be fixed with latest release.

**Comment by ghost** [comment]
not currently jailbroken but thanks for the heads up! appreciate it!
